### ISSUE TITLE
'J' missing in alpha_num_keys variable in code illustration 1.10

### ISSUE THREAD

**Issue by snowpuppy** [PacktPublishing/Tkinter-GUI-Application-Development-Blueprints-Second-Edition#2]
In code illustration 1.10.py, there is a variable named _alpha_num_keys_ declared that is missing letter 'J'. In it's place there is a duplicate of the letter 'G'.

See https://github.com/PacktPublishing/Tkinter-GUI-Application-Development-Blueprints-Second-Edition/blob/master/Chapter%2001/1.10.py

Line 37:
`alpha_num_keys = 'ABCDEFGHIGKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz123456789'`

**Comment by sonam-packt** [comment]
@snowpuppy I have made the changes on repository

Thank you!!
