### ISSUE TITLE
class imports missing from 2.05.py

### ISSUE THREAD

**Issue by snowpuppy** [PacktPublishing/Tkinter-GUI-Application-Development-Blueprints-Second-Edition#4]
When exercising the newly introduced find functionality in 2.05.py, the application throws the following exception because the new classes used have not been imported:
<pre>
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "2.05.py", line 31, in find_text
    search_toplevel = Toplevel(root)
NameError: name 'Toplevel' is not defined
</pre>

Problematic file:
https://github.com/PacktPublishing/Tkinter-GUI-Application-Development-Blueprints-Second-Edition/blob/master/Chapter%2002/2.05.py

**Comment by sonam-packt** [comment]
@snowpuppy I have made the changes in file.

Thank you
